server:
  port: 8084

logging:
  level:
    root: INFO
  loggers:
    org.springframework.web: DEBUG
  logstash:
    url: http://loki:3100/loki/api/v1/push
  config: classpath:logback.xml

limits_config:
  max_label_name_length: 1024
  max_label_value_length: 4096